### ISSUE TITLE
server端运行报错

### ISSUE THREAD

**Issue by wujunze** [slince/spike#10]
![image](https://user-images.githubusercontent.com/12997869/40957928-dab9ee88-68c9-11e8-8e33-13be093b6c5f.png)
```bash
[2018-06-05 14:07:13] INFO: The server is running ...
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Spike\Timer\Timer::activate() must be an instance of React\EventLoop\Timer\TimerInterface, instance of React\EventLoop\Timer\Timer given, called in /home/deploy/.config/composer/vendor/slince/spike/src/Timer/UseTimerTrait.php on line 29 and defined in /home/deploy/.config/composer/vendor/slince/spike/src/Timer/Timer.php:26
Stack trace:
#0 /home/deploy/.config/composer/vendor/slince/spike/src/Timer/UseTimerTrait.php(29): Spike\Timer\Timer->activate(Object(React\EventLoop\StreamSelectLoop), Object(React\EventLoop\Timer\Timer))
#1 /home/deploy/.config/composer/vendor/slince/spike/src/Server/Server.php(120): Spike\Server\Server->addTimer(Object(Spike\Server\Timer\ReviewClient))
#2 /home/deploy/.config/composer/vendor/slince/spike/src/Server/Application.php(93): Spike\Server\Server->run()
#3 /home/deploy/.config/composer/vendor/slince/spike/src/Server/Application.php(79): Spike\Server\Application->runServer()
#4 /home/deploy/.config/composer/vendor/slince/spike/src/Server/A in /home/deploy/.config/composer/vendor/slince/spike/src/Timer/Timer.php on line 26
```

php版本
```
[deploy@code-1000 ~]$ php -v
PHP 7.0.29 (cli) (built: Apr  1 2018 00:08:23) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.29, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by slince** [comment]
react/event-loop 版本更新的问题；

**Comment by wujunze** [comment]
怎么解决

**Comment by slince** [comment]
先
```bash
composer global remove slince/spike
```
主动安装 event-loop
```bash
composer global require  react/event-loop ^0.4
```

再安装spike

**Comment by wujunze** [comment]
你能不能在composer.json中限制 react/event-loop 版本  避免其他童鞋也遇到这个问题

**Comment by slince** [comment]
会的，spike还有一些已知的问题，后面有时间我会一起改掉；暂时先这么处理即可；

**Comment by wujunze** [comment]
OK  Thanks @slince

**Comment by slince** [comment]
重构版本已经发布，你可以试下；
